### ISSUE TITLE
The front panel code snippet no work also "working" functions freeze the app

### ISSUE THREAD

**Issue by rickasheye** [sakamoto-poteko/MinecraftServerStatus#1]
My visual studio says that the method class Ping Does not exist!

**Comment by sakamoto-poteko** [comment]
Which version of .Net are you using?

This project was originally targeted to .Net Core 1.x, if my memory is correct.

I'll re-target it to .Net Core 2.0 shortly.

**Comment by rickasheye** [comment]
@sakamoto-poteko i am using .NET 4.6.1

**Comment by sakamoto-poteko** [comment]
So, how did you use this library?

Did you clone the entire repository, build the entire solution, or did you reference MCServerStatus project in your own project?

**Comment by sakamoto-poteko** [comment]
I have retargeted the project and reorganized the project. The README file is updated as well. 

See 388902a.

**Comment by rickasheye** [comment]
@sakamoto-poteko i downloaded it through NuGet Using vs2018 or vs2017

**Comment by sakamoto-poteko** [comment]
I have published a new version of 2.0.0 of this package. It will be available in nuget shortly.
Please try the latest version. 

**Note some class and method names have changed**

https://www.nuget.org/packages/MCServerStatus/2.0.0#

**Comment by rickasheye** [comment]
ok thanks

**Comment by sakamoto-poteko** [comment]
Does the latest nuget package work for you?

**Comment by rickasheye** [comment]
yea no probs

**Comment by sakamoto-poteko** [comment]
Ok I'll close this issue now.

Thanks for reporting the problem
